### ISSUE TITLE
Generic Monitor Graph

### ISSUE THREAD

**Issue by haarp** [udda/multiload-ng#11]
Hello, thanks for continuing to develop this nifty plugin!

I have a feature request to expand the usefulness further. Xfce4 has the "genmon" panel plugin, which allows showing arbitrary script output directly on the panel. The same could be done with graphs.

Let's use 1000 as the maximum value, then have the defined script output something like:

    200 100 350

the graph would show 200/1000 (20%) in the first defined color, 10% as second color, 35% as third color and the rest with the background color. :)

**Comment by udda** [comment]
Hello! I've been working to this feature in the last few days. At the moment it's marked experimental but  you can test it with appropriate *./configure* flag. 

It will be called "parametric graph", and it will soon be marked stable. Expect this in lastest git code today, will push in a few hours :)

**Comment by udda** [comment]
Parametric graph has now stable status! You can test it with lastest git code.
In the future it will have the ability to parse multiple values, at the moment it handles programs/scripts that:
* exit with code 0
* output a single number to stdout
* and an optional message to stderr.

**Comment by haarp** [comment]
Ooh, nice, thanks a lot! This seems to be working well so far.

A few things I noticed while playing around with this version:

- It's not immediately apparent in the program what kind of output it expects. There's an i icon in the settings, but it doesn't show anything when clicked on/hovered over (GTK3 version)
- It only considers the integer part of float values
- Detailed tooltip shows this under Message: Runtime Error (func=(main),adr=43): Divide by zero
- Multiple values for multiple colors, and/or multiple parametric graphs would be kickass :)

**Comment by udda** [comment]
Yeah that works but it's not yet production ready :) glad to know you like it!

About your complains, most of them are already planned to do before release:
* Informative tooltip is still empty, just because I didn't have the time (same goes for GTK2). It will be filled soon with proper explanations.
* Nice idea to parse floats too, I didn't think about that! I will do it.
* *Message* part comes from the program in your command line. It's the contents of the first line of stderr.
* Multiple values with different colors (4 total values) are already on the way.

Stay tuned, and feel free to open another issue if something goes wrong. Thank you!
