### ISSUE TITLE
Tooltips no longer work in Xfce, LXDE and standalone applet

### ISSUE THREAD

**Issue by hotice** [udda/multiload-ng#18]
The tooltips no longer work with multiload-ng 1.3.0 in Xfce (tested in Xubuntu), LXDE (tested in Lubuntu), and the standalone applet. I tried setting them to both simple and advanced, both with the same result.

**Comment by udda** [comment]
I suppose this is a GTK+2 build. Could be useful to know whether this happens on GTK+3 too. I will try in a VM in a few hours.

**Comment by hotice** [comment]
Indeed, it was GTK2. Xubuntu and Lubuntu don't use GTK3 so I couldn't test that part, and in MATE it worked with both GTK2 and GTK3.

**Comment by udda** [comment]
Could you please try raising the update interval and see if tooltips show up?
In my tests, they do. Knowing this allows me to better locate the problem

**Comment by hotice** [comment]
Yes, increasing the update interval by just one step gets the tooltips to work.

**Comment by udda** [comment]
OK, then the culprit is a known GTK limitation (race between `query-tooltip` signal timeout and `gtk_widget_set_tooltip_text`).
I will fix that in next versions, as it requires some work: fixing needs building custom widgets and make them act as standard tooltips.

Exactly for this reason, for low update intervals, a warning icon pops up next to interval value.

At the moment, I adjusted the value which triggers the display of warning, so the user is informed of that. Also, I raised the default update interval from 500 ms to 1000 ms. Default configuration should now be OK. Closing.
