### ISSUE TITLE
Every update resets custom colors and won't accept format of previous saves

### ISSUE THREAD

**Issue by doublemeat** [udda/multiload-ng#22]
First of all, you are a godsend. I suffered through the Gnome2 and then MATE desktops, ONLY because of the gnome system-monitor applet! No other desktop or panel had anything close. (Well that and Metacity/Marco, which works fine in other desktop environments, at least XFCE.)

Then not only did you make something "close", you greatly _improved_ it. But that's not all! You also made it available for other panel environments, such as XFCE! A decade of prayers have been answered, I've finally been able to switch away from MATE.

OK but so far, my experience has been frustrating. Because every time I do an apt-get upgrade, Multiload-ng resets. Sometimes just colors, sometimes also selected monitors. But that would be totally OK, _if_ the "load color scheme" from previous saves, worked. Instead, every new version complains about incompatible settings from previous versions. I suppose I would be OK with that, with a young and evolving project, but I don't see any new features to justify it. (Well I did notice a significant change in configuration layout at one point, no comment on which I liked better, but otherwise I've noticed no other changes.)

You would be my mother of dragons, **if only you kept the color scheme import/export format the same or at least compatible across versions - or just compatible in the forward direction**!

I notice the file is in binary format. Why not just use XML? That way you could parse what you understand, ignore the rest, and would more more cross-version compatibility/stability. (I realize you could achieve the same idea with better handling of _any_ format. But there are alot of libraries for every/any dev environment to make XML handling a no-brainer.) That way, you could gradually add in new fields such as sensor and layout option saving, without compromising backward compatibility. I'd gladly suffer through another breaking update for that. Otherwise, next breaking change, I'm going to have to lock the version in apt. (But please do keep up the good work regardless!)

If you'd like help generating an XML settings file format, I'd gladly contribute. Otherwise, my C skills ain't what they used to be.

**Comment by udda** [comment]
Wow! Thank you! Words like these are a big source of motivation. I'm very happy to know that you are happy with my plugin (by the way, switching from GNOME 2 to XFCE was to me the main reason to start with Multiload-ng)

You know C, you look really interested and willing to help. You deserve a detailed response.

## About settings reset
That happened twice.

### From v1.1.0 to v1.2.0
Save path of settings changed. Multiload-ng used to put its files in user home directory; in v1.2.0 they were all moved to `$HOME/.config/multiload-ng/`, so at first launch all settings had to be recreated.

This cleaner approach allowed to store all required files, while not polluting home directory.
Moreover, I'm pretty sure that files location is now stable, so no more settings reset for this reason.

### From v1.2.0 to v1.3.0
Some settings changed name and/or meaning. So the old settings were still there, but were not read anymore. You are right, it was an internal (but necessary) change, with no visible effects.

Likewise, settings names are now supposed to be stable (although I can't guarantee that, but there must be a very good reason). However, if it were to happen again, it would reset only affected settings.

### Current situation
I now consider on-disk settings format pretty stable, so settings reset should not happen anymore, or at least will be limited to individual settings. In particular, **settings will not reset at all in next release**.

Nevertheless, being a *young and evolving project* as you noted, means that settings  might not be in their final format. I will try to minimize changes and possibly *group* them, in order to give less hassle as possible.

## About color scheme format
You are absolutely right about everything. Currently, color scheme format is just the C structure `MultiloadColorScheme` (defined in [colors.h](https://github.com/udda/multiload-ng/blob/master/common/colors.h)), put on file with `fwrite`.

When the struct changes (either by adding one member, or changing length of an array), the file format changes. I just increment `MULTILOAD_COLOR_SCHEME_VERSION`, and this makes the file incompatible with other (past or future) versions.

### Rationale
This is a naive approach, with much room for improvement. These are the reasons that made me choose this format:
- simplicity of implementation, no external libraries
- fast load/save
- no parsing, means removing an entire source of potential errors

Downsides I found so far:
- not extensible at all
- stores `double` values directly, means potential incompatibilities between different architectures/compilers

### The future
I was already planning to change that with a version-independent format. XML is a totally viable option.

If you'd like to provide a patch, pull request, or even just some hints to speed up adoption of a new format, you are welcome. Anyhow, it's already on my TODO list so don't worry, it will be done sooner or later.

Thank you for your feedback. Hopefully next color scheme format version will be the last :wink:

**Comment by udda** [comment]
While the version-independent format is in internal development, I recently added a [compatibility layer](https://github.com/udda/multiload-ng/commit/399f7c67bd3e82eb68b89134bef63e821ae09027) which allow to load color schemes created with older versions of Multiload-ng.

Although I could only test the current release (1.3.1) vs git code (color scheme version 4 to version 5), this should work with older versions too.

**Comment by doublemeat** [comment]
Awesome, thanks for the detailed response! Keep up the good work!
It's been over two decades since I've programmed in C, so I wouldn't be of much use to you in providing a patch :-(

**Comment by udda** [comment]
You are already helping a lot, with all these open issues :smile:
