### ISSUE TITLE
Temperature graph source missing

### ISSUE THREAD

**Issue by spvkgn** [udda/multiload-ng#29]
It seems like a bug, please see screenshot https://i.imgur.com/WNWf5yt.png
lm-sensors works fine. Ubuntu 12.04 32-bit, multiload-ng 1.4.2

**Comment by udda** [comment]
Could you please post the output of `sensors`?

**Comment by spvkgn** [comment]
```
~ $ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +41.0°C  (high = +76.0°C, crit = +100.0°C)
Core 1:       +37.0°C  (high = +76.0°C, crit = +100.0°C)

it8718-isa-0290
Adapter: ISA adapter
CPU Vcore:    +1.06 V  (min =  +0.85 V, max =  +1.34 V)
DDR18V:       +1.92 V  (min =  +1.71 V, max =  +1.98 V)
+3.3Vsb:      +3.31 V  (min =  +3.14 V, max =  +3.47 V)
+5V:          +4.89 V  (min =  +4.76 V, max =  +5.24 V)
+12V:        +12.16 V  (min = +11.39 V, max = +12.61 V)
Vbat:         +2.80 V  
CPU Fan:     1155 RPM  (min =  600 RPM)
M/B Temp:     +45.0°C  (low  =  +0.0°C, high = +106.0°C)  sensor = thermistor
CPU Temp:     +34.0°C  (low  = +25.0°C, high = +65.0°C)  sensor = thermal diode
CPU VID:     +1.100 V
```

**Comment by udda** [comment]
That's strange. I just tested Multiload-ng 1.4.2 on Ubuntu 12.10.5 (32 bit), and temperature sources are showing correctly. Could you provide me some additional data?

Please answer these questions
- Is your Ubuntu a fresh install or a long used system?
- Is your Ubuntu updated?
- What is the brand of your processor? (Intel, AMD, ...)

Please post the output of these commands:
- `ls -l /sys/class/thermal/ /sys/class/hwmon/`
- `ls -l /sys/class/thermal/*/ /sys/class/hwmon/*/`

**Comment by spvkgn** [comment]
It installed since 2012 and updated, Intel CPU.

```
~ $ ls -l /sys/class/thermal/ /sys/class/hwmon/
/sys/class/hwmon/:
итого 0
lrwxrwxrwx 1 root root 0 окт.  17 14:01 hwmon0 -> ../../devices/platform/coretemp.0/hwmon/hwmon0
lrwxrwxrwx 1 root root 0 окт.  17 14:01 hwmon1 -> ../../devices/platform/it87.656/hwmon/hwmon1

/sys/class/thermal/:
итого 0
lrwxrwxrwx 1 root root 0 окт.  18 08:28 cooling_device0 -> ../../devices/virtual/thermal/cooling_device0
lrwxrwxrwx 1 root root 0 окт.  18 08:28 cooling_device1 -> ../../devices/virtual/thermal/cooling_device1
~ $ ls -l /sys/class/thermal/*/ /sys/class/hwmon/*/
/sys/class/hwmon/hwmon0/:
итого 0
lrwxrwxrwx 1 root root    0 окт.  17 14:01 device -> ../../../coretemp.0
drwxr-xr-x 2 root root    0 окт.  17 14:01 power
lrwxrwxrwx 1 root root    0 окт.  17 14:01 subsystem -> ../../../../../class/hwmon
-rw-r--r-- 1 root root 4096 окт.  17 14:01 uevent

/sys/class/hwmon/hwmon1/:
итого 0
lrwxrwxrwx 1 root root    0 окт.  17 14:01 device -> ../../../it87.656
drwxr-xr-x 2 root root    0 окт.  17 14:01 power
lrwxrwxrwx 1 root root    0 окт.  17 14:01 subsystem -> ../../../../../class/hwmon
-rw-r--r-- 1 root root 4096 окт.  17 14:01 uevent

/sys/class/thermal/cooling_device0/:
итого 0
-rw-r--r-- 1 root root 4096 окт.  18 08:28 cur_state
lrwxrwxrwx 1 root root    0 окт.  18 08:28 device -> ../../../LNXSYSTM:00/LNXCPU:00
-r--r--r-- 1 root root 4096 окт.  18 08:28 max_state
drwxr-xr-x 2 root root    0 окт.  18 08:28 power
lrwxrwxrwx 1 root root    0 окт.  18 08:28 subsystem -> ../../../../class/thermal
-r--r--r-- 1 root root 4096 окт.  18 08:28 type
-rw-r--r-- 1 root root 4096 окт.  18 08:28 uevent

/sys/class/thermal/cooling_device1/:
итого 0
-rw-r--r-- 1 root root 4096 окт.  18 08:28 cur_state
lrwxrwxrwx 1 root root    0 окт.  18 08:28 device -> ../../../LNXSYSTM:00/LNXCPU:01
-r--r--r-- 1 root root 4096 окт.  18 08:28 max_state
drwxr-xr-x 2 root root    0 окт.  18 08:28 power
lrwxrwxrwx 1 root root    0 окт.  18 08:28 subsystem -> ../../../../class/thermal
-r--r--r-- 1 root root 4096 окт.  18 08:28 type
-rw-r--r-- 1 root root 4096 окт.  18 08:28 uevent
```

**Comment by udda** [comment]
You system acts in a unusual way. I have the same temperature sensor as yours, and it works for me.

Could you try running Multiload-ng from a Live CD / fresh install?

-------
*Technical details below, you can skip them.*

### Working principle
Multiload-ng reads temperature data through Linux **hwmon** interface, which collects all sensors in the system. Using hwmon allows to read from all temperature sensors without having to specifically support any of them.

(As a special case, **acpitz** driver - ACPI thermal zones - is directly supported as fallback, but it's not your case)

### About the the issue
You have two temperature drivers: **coretemp** and **it87.656**, both supported by hwmon.

Your system appears to support **hwmon** interface, but for some reason it isn't storing temperatures there. There should be files with this pattern: `/sys/class/hwmon/hwmon*/temp*`

`sensors` directly read temperature from each driver, that's why it works. I'm not planning of add platform-specific code unless it's strictly necessary.

**Comment by udda** [comment]
Have you tried Multiload-ng in a *Ubuntu Precise* live CD? In my tests everything works. This could help to narrowing the source of the problem.

**Comment by spvkgn** [comment]
I will try as soon as possible (don't have .iso so far), sorry for the delay with answer.

**Comment by spvkgn** [comment]
I've tried with 16.10 livecd - it works fine there, therefore I decide to close the issue.

**Comment by udda** [comment]
I am sorry that it doesn't work well in your system. I am really unable to fix your issue because (as you discovered) it does not depend from Multiload-ng, and I don't have any clue...

All I can say is that the culprit is very likely to be the running kernel (as it's the entity that manages `/sys/class/hwmon`). You can try to up/downgrade it (or simply boot with a different kernel, Ubuntu retains older kernels on upgrade), and see if that solves your issue.

I am willing to help you as best as I can :smile:

**Comment by spvkgn** [comment]
Thanks for your suggestion, I'll attempt it. Many thanks for your help and for this great project!

**Comment by butty2017** [comment]
Hi, I see a similar problem.

Linux version: Linux Mint 18.1
xfce4-multiload-ng-plugin version: 1.5.2-1~webupd8~xenial0

Problem: Wrong temp. source is used when booting Linux with GRUB_CMDLINE_LINUX="acpi_enforce_resources=lax".

Example: When temp. source is set to "Physical id 0", "AUXTIN" is used actually.

Note: When the grub option is not specified, it's ok.

Regards.

**Comment by udda** [comment]
Hello @butty2017, thanks for your feedback.

You are commenting over a closed issue. A comment here is likely to be forgotten with time.

Since your problem appears new and different from this one, would you mind to open a new issue? You can write exactly the same text if you want. This way we can better track the problem. Thank you!
