### ISSUE TITLE
Settings dialog: "Update interval" won't accept typed input

### ISSUE THREAD

**Issue by doublemeat** [udda/multiload-ng#32]
Multiload-ng 1.4.0.

The input boxes will allow the values to be deleted/added/changed, but when it loses focus, the value goes back to whatever it was before the change. Only using the "up/down" arrows, or up/down arrow keys on keyboard, seem to work.

For me, this is a very minor niggle and the workaround is easy.

**Comment by udda** [comment]
Thanks for the report!

I have not implemented it yet, for the following reason: due to localization support, the string that describes update interval (`%d milliseconds`) is not constant, that caused me some headaches when I tried to parse it.

Nonetheless, since an user is requesting it, I will try again :)

The workaround here is to type in **only** the desired number, deleting any other text, e.g. try to type directly `2000` and not `2000 milliseconds`.

The same goes for graph size.

**Comment by udda** [comment]
I managed to succeed in parsing user input like you described (the method I described in previous comment still works).
