### ISSUE TITLE
Settings dialog: "Timespan" is potentially misleading

### ISSUE THREAD

**Issue by doublemeat** [udda/multiload-ng#33]
While creating this issue I _just_ realized what is meant by the heading "Timespan": It is the update interval * pixel width. For a long time I had assumed it meant a "human" expression of the milliseconds. Which, obviously, didn't match up. (E.g. 2000 milliseconds is not = "1m 20s".) This bug was going to be that the values in the column were obviously wrong. So rather than that, it is that the column heading label "Timespan" should be something less potentially misleading.

And also I'm at a loss for a suggestion of a better word or short phrase that would fit.

Lowest possible priority.

**Comment by udda** [comment]
I understand your confusion. I was thinking about a better naming of that column literally for *weeks*, before giving up and settling with "timespan".

I agree with you that it is very misleading. The problem is that we can't use much longer strings, as I received many complains about *Preferences window too large* in the past.

Any suggestion is highly welcome...

**Comment by doublemeat** [comment]
Yeah that's a tough one! I've been in that exact boat before.

One possible solution would be to just remove the column altogether. When I didn't know what the column meant, it obviously wasn't adding any value and I never found myself asking the question the column answers. That's just one anecdote though, not evidence ;-).

Although I don't like Apple products (except macbooks), I think there's some benefit to their overall approach, in some aspects.  I often find myself thinking, "if this feature could be confusing or add clutter, what's the worst outcome of not including it? Would it's omission be glaring?"

**Comment by udda** [comment]
You could be right. The original purpose of the *timespan* column was to let user configure graphs in order to make they all show the same time frame, even when they have different sizes. Now I realize that this feature may not be as useful as I initially thought.

I'm inclined to follow your suggestion. If that proposal does not receive any objections within the next hours, *timespan* column will be gone!

**Comment by doublemeat** [comment]
That's funny, because I actually configure it that way - 40 px graphs with 2000 ms update, and 20 px graphs with 4000 ms update interval. I guess I didn't notice that the "Timespan" was the same :-). For me at least, who wants a little more advanced tinkering, the math seemed obvious enough. Why I didn't realize earlier what "Timespan" meant, then, is still a mystery.

**Comment by udda** [comment]
The column was removed! The naming problem is technically "solved" :sunglasses:
